import type { Metadata } from "next";
import { Roboto_Mono, Roboto_Serif, DM_Sans } from "next/font/google";
import "./globals.css";
import AppHeader from "./components/AppHeader";
import { Toaster } from "@/components/ui/sonner";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  display: "swap",
});

const robotoSerif = Roboto_Serif({
  variable: "--font-roboto-serif",
  subsets: ["latin"],
  display: "swap",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dishy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontVariables = `${robotoMono.variable} ${robotoSerif.variable} ${dmSans.variable}`;
  return (
    <html lang="en" className={fontVariables}>
      <body className="antialiased">
        <AppHeader />
        <div className="layout-content">
          {children}
        </div>
        <Toaster />
      </body>
    </html>
  );
}
